config/routes.rb
Rails.application.routes.draw do
  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)

  # devise_for :users
    devise_for :users, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }

  root to: "restaurants#index"


  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

   resource :profile, controller: 'users', as: 'current_user_profile'

  resources :categories

  resources :restaurants  do
    get 'my_restaurants_list', on: :collection
  end

  # resources :restaurants
   resources :carts

  resources :dishes do
    collection do
      get 'owner_dishes'
      get 'filter', action: :index
    end
  end

  resources :orders do
    post 'create_payment', action: :create_payment, on: :member
  end
end



      # resources :orders, only: %i[index new create show destroy] do
      #   resources :order_items, only: [:index]
      #   get '/payment', action: :payment, on: :member
      # end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         # for Google OmniAuth
         :omniauthable, omniauth_providers: [:google_oauth2,:facebook, :twitter,:github]
  validates :type, inclusion: { in: %w[Owner Customer] }
  validates :name, :email, :password, presence: true
  validates :email, uniqueness: true,
                    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: 'Invalid email id!!!!' }

  validates :phone_number,
      presence: true,
      uniqueness: true,format: { with: /\d[0-9]\)*\z/ }
  has_one_attached :picture

  # def self.ransackable_attributes(auth_object = nil)
  #   ["created_at", "email", "encrypted_password", "id", "name", "password", "remember_created_at", "reset_password_sent_at", "reset_password_token", "type", "updated_at"]
  # end

  # def self.ransackable_associations(auth_object = nil)
  #   ["picture_attachment", "picture_blob"]
  # end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
      user.avatar_url = auth.info.image
      user.type ||= 'Customer'
      # user.contact = auth.info.contact
      unless user.save
        puts "Error saving user: #{user.errors.full_messages.join(', ')}"
      end
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && self.provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

  def has_no_password?
    self.encrypted_password.blank?
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
    def google_oauth2
      user = User.from_omniauth(auth)
      if user.present?
        sign_out_all_scopes
        flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect user, event: :authentication
      else
        flash[:alert] =
          t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
        redirect_to new_user_session_path
      end
    end

    def facebook
      @user = User.from_omniauth(request.env['omniauth.auth'])
      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url
      end
    end

    def twitter
      @user = User.from_omniauth(request.env["omniauth.auth"])

      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      else
        session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
        redirect_to new_user_registration_url
      end
    end

    def github
      @user = User.from_omniauth(request.env["omniauth.auth"])
      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
      else
        session["devise.github_data"] = request.env["omniauth.auth"].except("extra")
        redirect_to new_user_registration_url
      end
    end

    def failure
      redirect_to root_path
    end



    protected
    def after_omniauth_failure_path_for(_scope)
      new_user_session_path
    end

    def after_sign_in_path_for(resource_or_scope)
      stored_location_for(resource_or_scope) || root_path
    end
    private
    def auth
      @auth ||= request.env['omniauth.auth']
    end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def update_resource(resource, params)
    if resource.provider == 'google_oauth2'
      params.delete('current_password')
      resource.password = params['password']
      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
  class UsersController < ApplicationController
    # before_action :authenticate_request, except: %i[create login forgot_password reset_password]

    def index
      @users =  User.all
    end

    def create
      user = User.new(user_params)
      if user.save
        # UserMailer.with(user: user).welcome_email.deliver_now
        # flash.notice = 'the account  successfully saved'
        render json: user, status: :created
      else
        render json: { error: user.errors.full_messages }, status: :unprocessable_entity
      end
    end

    def show
      @current_user
    end

    def update
      if @current_user.update(user_params)
        render json: { data: @current_user, message: 'User updated' }
      else
        render json: { error: @current_user.errors.full_messages }, status: :unprocessable_entity
      end
    end


    def destroy
      if @current_user.destroy
        render json: { data: @current_user,message: 'User deleted' }
      else
        render json: { error: 'User deletion failed' }
      end
    end


    private

    def user_params
      params.require(:user).  permit(:name, :email, :phone_number, :password, :type,:picture)
    end
  end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/edit.html.erb
  <h1>Edit User Profile</h1>
<%= form_for @current_user, url: current_user_profile_path, method: :patch do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>
<!--   <div class="form-group">
    <%= f.label :picture %>
    <%= f.file_field :picture, class: 'form-control' %>
  </div> -->
  <%= f.submit 'Update Profile', class: 'btn btn-primary' %>
<% end %>
<%= link_to 'Back to User Profile', current_user_profile_path, class: 'btn btn-default' %>



s

app/views/users/index.html.erb
<% if user_signed_in? %>
      <%= link_to "Sign out", destroy_user_session_path %> <br />
<%end %>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |r| %>
      <tr>
        <td><%= r.name %></td>
        <td><%= r.type %></td>
        <td><%= r.email %></td>
         </tr>
    <% end %>
  </tbody>
</table>


<%= link_to "Back", restaurants_path, class: 'btn btn-primary' %>

app/views/users/show.html.erb
<body>
  <h1>User Profile</h1>
  <p><strong>ID:</strong> <%= current_user.id %></p>
  <p><strong>Name:</strong> <%= current_user.name %></p>
  <p><strong>Email:</strong> <%= current_user.email %></p>
  <p><strong>User Phone_number:</strong> <%= current_user.phone_number %></p>
  <p><strong>User Type:</strong> <%= current_user.type %></p>


  <%= link_to "Back", restaurants_path, class: 'btn btn-secondary' %>

  <% if current_user.type == "Owner" %>
    <%= link_to "Show My Restaurants", my_restaurants_list_restaurants_path, class: 'btn btn-primary' %>
    <%= link_to "Show on restaurants dishes", owner_dishes_dishes_path, class: 'btn btn-primary' %>


  <% end %>

  <%= button_to "EDIT PROFILE", edit_user_registration_path, method: :get, class: "button-shape" %>
</body>









 <style>
   body {
     font-family: 'Arial', sans-serif;
     margin: 0;
     padding: 0;
     background-color: #f8f9fa;
     color: #495057;
   }

   h1 {
     font-size: 36px;
     color: #007bff;
     margin-bottom: 20px;
   }

   p {
     font-size: 18px;
     margin-bottom: 10px;
   }

   .btn-secondary,
   .btn-primary,
   .button-shape {
     padding: 12px 24px; /* Increased padding for a more clickable area */
     margin: 5px; /* Added margin for spacing */
     text-align: center;
     display: inline-block;
     text-decoration: none;
     cursor: pointer;
     border-radius: 5px;
     font-size: 16px;
   }

   .btn-secondary {
     background-color: #6c757d;
     color: #fff;
   }

   .btn-secondary:hover {
     background-color: #5a6268;
   }

   .btn-primary {
     background-color: #007bff;
     color: #fff;
     margin-right: 10px;
   }

   .btn-primary:hover {
     background-color: #0056b3;
   }

   .button-shape {
     background-color: #28a745;
     color: #fff;
   }

   .button-shape:hover {
     background-color: #218838;
   }
 </style>